### ISSUE TITLE
Do you have realisation of reCAPTCHA (with proxy to)?

### ISSUE THREAD

**Issue by maxlen** [reilag/php-anticaptcha#2]

**Comment by reilag** [comment]
No, I have not realisation of reCAPTCHA right now. 
But planing reales new Library it in two week.

**Comment by m-tymchyk** [comment]
Version 2.0.0 supports reCaptcha with proxy :)



```php
$reCaptchaV2Task = new \AntiCaptcha\Task\RecaptchaV2Task(
    "http://makeawebsitehub.com/recaptcha/test.php",     // <-- target website address
    "6LfI9IsUAAAAAKuvopU0hfY8pWADfR_mogXokIIZ"           // <-- recaptcha key from target website
);

$reCaptchaV2Task->setProxy(
    "8.8.8.8",
    1234,
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116",
    "http",
    "login",
    "password",
    null // also you can add cookie
);
```

**Comment by m-tymchyk** [comment]
Version 2.0.0 supports reCaptcha with proxy :)

$reCaptchaV2Task = new \AntiCaptcha\Task\RecaptchaV2Task(
    "http://makeawebsitehub.com/recaptcha/test.php",     // <-- target website address
    "6LfI9IsUAAAAAKuvopU0hfY8pWADfR_mogXokIIZ"           // <-- recaptcha key from target website
);

$reCaptchaV2Task->setProxy(
    "8.8.8.8",
    1234,
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116",
    "http",
    "login",
    "password",
    null // also you can add cookie
);
