### ISSUE TITLE
Logger fix

### ISSUE THREAD

**Issue by dmitryuk** [reilag/php-anticaptcha#4]
I have found a problem if debug is false
You can see where is no check if debugMod
https://github.com/m-tymchyk/php-anticaptcha/blob/master/src/AntiCaptcha.php#L370
Overwise error
```Call to a member function debug() on null```

**Comment by dmitryuk** [comment]
Нашел мерж но что то не двигается
https://github.com/m-tymchyk/php-anticaptcha/pull/3

**Comment by m-tymchyk** [comment]
Сам случайно на него наткнулся и уже смерджил
